### ISSUE TITLE
ENV not working with docker-compose env_file

### ISSUE THREAD

**Issue by zx1986** [phusion/passenger-docker#153]
docker-compose.yml
```
my_rails:
  image: rails
  container_name: rails
  restart: always
  volumes:
    - ./:/home/app
  ports:
    - "8080:80"
  env_file:
    - docker.env
```

docker.env
```
SECRET_KEY_BASE=xxxxxxx
```

Error:
```
rails    |   Error details saved to: /tmp/passenger-error-Q9N1Wk.html
rails    |   Message from application: Devise.secret_key was not set. Please add the following to your Devise initializer:
```

devise.rb
```
config.secret_key = ENV["SECRET_KEY_BASE"]
```

And I login the shell of the container:
```
> echo $SECRET_KEY_BASE
> xxxxxxx
```

what's going on here?
