### ISSUE TITLE
\"exec: \\\"rails\\\": executable file not found in $PATH\"\n"

### ISSUE THREAD

**Issue by amingilani** [phusion/passenger-docker#161]
I can't seem to run the `rails` command from outside the container, even though it's definitely in the `$PATH`

```
$ docker-compose run webapp rails db:setup
ERROR: Cannot start service webapp: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"rails\\\": executable file not found in $PATH\"\n"
```

However, `rails` is certainly available from inside the container.
```
$ docker-compose run webapp bash

# root@f5815dc82edd:/home/app/webapp# which rails
/usr/local/rvm/gems/ruby-2.3.1/bin/rails

# root@f5815dc82edd:/home/app/webapp# $PATH
bash: /usr/local/rvm/gems/ruby-2.3.1/bin:/usr/local/rvm/gems/ruby-2.3.1@global/bin:/usr/local/rvm/rubies/ruby-2.3.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/rvm/bin: No such file or directory
root@f5815dc82edd:/home/app/webapp#
```

Infact, I can run `rake` from outside the container.

```
$ docker-compose run webapp rake db:setup
Created database 'myapp_development'
Created database 'myapp_test'
```

But `rails` commands are still unavailable

```
$ docker-compose run webapp rails g migration helloWorld
ERROR: Cannot start service webapp: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"rails\\\": executable file not found in $PATH\"\n"
```

Dockerfile
-----------

```
FROM phusion/passenger-ruby23

# Set correct environment variables.
ENV HOME /root

# Use baseimage-docker's init process.
CMD ["/sbin/my_init"]

# additional packages
RUN apt-get update

# Active nginx
RUN rm -f /etc/service/nginx/down

# Install bundle of gems
WORKDIR /tmp
ADD Gemfile /tmp/
ADD Gemfile.lock /tmp/
RUN bundle install

# Copy the nginx template for configuration and preserve environment variables
RUN rm /etc/nginx/sites-enabled/default

# Add the nginx site and config
ADD webapp.conf /etc/nginx/sites-enabled/webapp.conf

RUN mkdir /home/app/webapp
COPY . /home/app/webapp
RUN usermod -u 1000 app
RUN chown -R app:app /home/app/webapp
WORKDIR /home/app/webapp

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
EXPOSE 80
```

docker-compose.yml
---------------------

```
version: '2'
services:
  webapp:
    build: .
    container_name: myapp
    working_dir: /home/app/webapp
    ports:
      - "80:80"
    environment:
      - PASSENGER_APP_ENV=development
    volumes:
      - .:/home/app/webapp
    networks:
      - back-end
  db:
    container_name: db
    image: postgres:9.4
    networks:
      - back-end
networks:
  back-end:
    driver: bridge
```
