### ISSUE TITLE
Cache bundled gems?

### ISSUE THREAD

**Issue by juanpastas** [phusion/passenger-docker#192]
I used this:

```
# Dockerfile
ENV BUNDLE_PATH /deps/bundler
```

And this:

```
# docker-compose.yml
services:
  passenger:
    build: .
    volumes:
      - .:/home/app/webapp
      - ./docker/nginx-site.conf:/etc/nginx/sites-enabled/default
      - deps:/deps
volumes:
  deps:
```

And Dockerfile entrypoint is:

```
bundle install
bundle exec rake db:create db:migrate db:seed
bundle exec rake assets:precompile
echo "====> User is $(whoami)"
echo "====> RAILS_ENV is $RAILS_ENV"
/sbin/my_init

```

All of this makes gems to be installed on docker volume which is mounted at `/deps`.

But when going to localhost:3000, I am getting an error because passenger is using a different gems folder:

```
Message from application: <p>It looks like Bundler could not find a gem. Maybe you didn't install all the gems that this application needs. To install your gems, please run:</p>
passenger_1  | 
passenger_1  |   <pre class="commands">bundle install</pre>
passenger_1  | 
passenger_1  | <p>If that didn't work, then the problem is probably caused by your application being run under a different environment than it's supposed to. Please check the following:</p>
passenger_1  | 
passenger_1  | <ol>
passenger_1  |   <li>Is this app supposed to be run as the <code>app</code> user?</li>
passenger_1  |   <li>Is this app being run on the correct Ruby interpreter? Below you will
passenger_1  |       see which Ruby interpreter Phusion Passenger attempted to use.</li>
passenger_1  |   <li>Please check whether the correct RVM gemset is being used.</li>
passenger_1  |   <li>Sometimes, RVM gemsets may be broken.
passenger_1  |       <a href="https://github.com/phusion/passenger/wiki/Resetting-RVM-gemsets">Try resetting them.</a></li>
passenger_1  | </ol>
passenger_1  | 
passenger_1  | <p>-------- The exception is as follows: -------</p>
passenger_1  | Could not find rake-12.0.0 in any of the sources (Bundler::GemNotFound)
passenger_1  | <pre>  /usr/local/rvm/gems/ruby-2.3.3@global/gems/bundler-1.15.1/lib/bundler/spec_set.rb:87:in `block in materialize&#39;
passenger_1  |   /usr/local/rvm/gems/ruby-2.3.3@global/gems/bundler-1.15.1/lib/bundler/spec_set.rb:81:in `map!&#39;
passenger_1  |   /usr/local/rvm/gems/ruby-2.3.3@global/gems/bundler-1.15.1/lib/bundler/spec_set.rb:81:in `materialize&#39;
passenger_1  |   /usr/local/rvm/gems/ruby-2.3.3@global/gems/bundler-1.15.1/lib/bundler/definition.rb:159:in `specs&#39;
passenger_1  |   /usr/local/rvm/gems/ruby-2.3.3@global/gems/bundler-1.15.1/lib/bundler/definition.rb:218:in `specs_for&#39;
passenger_1  |   /usr/local/rvm/gems/ruby-2.3.3@global/gems/bundler-1.15.1/lib/bundler/definition.rb:207:in `requested_specs&#39;
```

It works if I `cp -r /deps/bundler/* /usr/local/rvm/gems/ruby-2.3.3`, but that will cause problems for new gems.

Is there a way I can cache bundled gems?

**Comment by maurosbu** [comment]
Can you please provide nginx-site.conf content? 
What about executing

    bundle install --path=${BUNDLE_PATH}

instead of

    bundle install

?

I'm using the same approach successfully. I have a dozen of rails apps that share gems saved in a volume.

Mauro

**Comment by shaliko** [comment]
@juanpastas you just need cache in volume rvm folder.

My docker-compose.yml file

```
version: '2'
services:
  web:
    build: .
    ports:
      - '80:80'
    volumes:
      - .:/home/app/web:z
      - rvm_gems:/usr/local/rvm/gems/ruby-2.4.1@networking
    env_file:
      - docker/env.web
    depends_on:
      - 'postgres'
  postgres:
    image: 'postgres:9.5'
    env_file:
       - 'docker/env.postgres'
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: {}
  mysql: {}
  rvm_gems: {}
```

In your case, you just need replace one line to:

```
- rvm_gems:/usr/local/rvm/gems/ruby-2.3.3@global
```
